services:
  - type: web
    name: stone-paper-scissors-game
    env: node
    plan: free
    buildCommand: |
      cd client && npm ci && npm run build && 
      cd ../server && npm ci
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: stone-paper-scissors-game
          property: port
      - key: CLIENT_URL
        fromService:
          type: web
          name: stone-paper-scissors-game
          property: host